name: Bin
author: EzMinh
version: 1.0.4
api: [3.14.0]
main: EzMinh\Bin\Main

commands:
  bin:
    description: Remove items
    permissions: bin.cmd

permissions:
  bin.cmd:
    description: Allows player to use /bin
    default: true
    